services:
  - type: web
    name: tukuy-faceapi
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        libjpeg-dev zlib1g-dev libpng-dev libopenblas-dev liblapack-dev cmake g++ make \
        && pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
